[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "jerem", email = "jeremydeproote@hotmail.com"},
]
dependencies = [
    "black>=23.1.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
